export default {
    //--- SYSTEM --//
    SET_ERROR: 'SET_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',
    DELAY_PAGE: 'DELAY_PAGE',
    RECEIVE_CONFIG: 'RECEIVE_CONFIG',
    //--- ABOUT ---//
    RECEIVE_PERSONAL_DATA: 'RECEIVE_PERSONAL_DATA',
    RECEIVE_BUSINESS_DATA: 'RECEIVE_BUSINESS_DATA',
    RECEIVE_SUBSCRIBE_DATA: 'RECEIVE_SUBSCRIBE_DATA',
    RECEIVE_WIDGETS_DATA: 'RECEIVE_WIDGETS_DATA',
    //--- BLOG ---//
    RECEIVE_BLOG_POSTS: 'RECEIVE_BLOG_POSTS',
    RECEIVE_BLOG_POST: 'RECEIVE_BLOG_POST',
    RECEIVE_BLOG_CATEGORIES: 'RECEIVE_BLOG_CATEGORIES',
    RECEIVE_BLOG_POPULAR: 'RECEIVE_BLOG_POPULAR',
    //--- SLIDER ---//
    RECEIVE_SLIDER: 'RECEIVE_SLIDER',
    //--- CUSTOMERS ---//
    RECEIVE_CUSTOMERS: 'RECEIVE_CUSTOMERS',
    //--- GALLERY ---//
    RECEIVE_GALLERY: 'RECEIVE_GALLERY',
    RECEIVE_INSTAGRAM: 'RECEIVE_INSTAGRAM',
    //--- SERVICES ---//
    RECEIVE_SERVICES_HOME: 'RECEIVE_SERVICES_HOME',
    RECEIVE_SERVICES_ACCORDION: 'RECEIVE_SERVICES_ACCORDION',
    RECEIVE_SERVICES_LIST: 'RECEIVE_SERVICES_LIST',
    RECEIVE_SERVICES_PANELS: 'RECEIVE_SERVICES_PANELS',
    RECEIVE_SERVICES_TABS: 'RECEIVE_SERVICES_TABS',
    RECEIVE_SERVICES_PURCHASE: 'RECEIVE_SERVICES_PURCHASE',
    //--- TEAM ---//
    RECEIVE_TEAM_INFO: 'RECEIVE_TEAM_INFO',
    RECEIVE_TEAM_MEMBERS: 'RECEIVE_TEAM_MEMBERS',
    RECEIVE_TEAM_SUMMARY: 'RECEIVE_TEAM_SUMMARY',
    //--- TESTIMONIALS ---//
    RECEIVE_TESTIMONIALS: 'RECEIVE_TESTIMONIALS',
    //--- SOCIALS ---//
    RECEIVE_MY_SOCIALS: 'RECEIVE_MY_SOCIALS',
    RECEIVE_SHARE_SOCIALS: 'RECEIVE_SHARE_SOCIALS',
    RECEIVE_TWITTER: 'RECEIVE_TWITTER',
    //--- FAQ ---//
    RECEIVE_FAQ: 'RECEIVE_FAQ',
    //--- WELCOME ---//
    RECEIVE_WELCOME: 'RECEIVE_WELCOME',
    //--- PRICING ---//
    RECEIVE_PRICING: 'RECEIVE_PRICING',
    //--- PORTFOLIO ---//
    RECEIVE_PORTFOLIO_ITEMS: 'RECEIVE_PORTFOLIO_ITEMS',
    RECEIVE_PORTFOLIO_ITEM: 'RECEIVE_PORTFOLIO_ITEM',
}


